Map<String, String>subjectsMap = {
  "gd": "Godsdienst",
  "schk": "Scheikunde",
  "sk": "Scheikunde",
  "na": "Natuurkunde",
  "nat": "Natuurkunde",
  "biol": "Biologie",
  "bi": "Biologie",
  "in": "Informatica",
  "wi": "Wiskunde",
  "wisa": "Wiskunde A",
  "wisb": "Wiskunde B",
  "wisc": "Wiskunde C",
  "wisd": "Wiskunde D",
  "ne": "Nederlands",
  "netl": "Nederlandse Taal",
  "entl": "Engelse Taal",
  "en": "Engels",
  "fatl": "Franse Taal",
  "fa": "Frans",
  "dutl": "Duitse Taal",
  "du": "Duits",
  "anw": "Algemene Natuurwetenschappen",
  "mo": "Management & Onderneming",
  "econ": "Economie",
  "eco": "Economie",
  "ec": "Economie",
  "beco": "Bedrijfseconomie",
  "ckv": "Culturele en Kunstzinnige Vorming",
  "ges": "Geschiedenis",
  "gs": "Geschiedenis",
  "ak": "Aardrijkskunde",
  "lo": "Lichamelijke Opvoeding",
  "bsm": "Bewegen, Sport en Maatschappij",
  "tovo": "Toerusting en Vorming",
  "maat": "Maatschappijleer",
  "mod": "Module",
  "bg": "Begleiding",
  "proj": "Project"

};